### ISSUE TITLE
Contrast measurements do not work in 

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#67] opened 2016-08-05 19:32 UTC
I get this error when I choose the Contrast button from the ImageInfo menu when looking at a Stokes Data Cube: 

% Unable to dereference NULL pointer: <POINTER  (<NullPointer>)>.

% Execution halted at:  GPITV::CONTRPROF_REFRESH 18406 /Users/Max/Library/GPI/gpitv/gpitv__define.pro

%                       GPITV::CONTRAST  18715 /Users/Max/Library/GPI/gpitv/gpitv__define.pro

%                       GPITV::TOPMENU_EVENT 1512 /Users/Max/Library/GPI/gpitv/gpitv__define.pro

%                       GPITVO_MENU_EVENT  530 /Users/Max/Library/GPI/gpitv/gpitv__define.pro

%                       $MAIN$

**Comment by mperrin** [comment] 2016-08-05 21:28
Duplicate of #18

**Closed as completed by mperrin** 2016-08-05 21:28 UTC
Labels: bug, wontfix
