### ISSUE TITLE
bug into contrast plot GPItv

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#80] opened 2016-08-05 20:18 UTC
The autoreducer crashed at 4am on the last night of the may commissioning run when switching between two images while displaying a contrast plot.  Error message below:

% GPIDRFPARSER::ENDDOCUMENT: XML parsing complete.
% PARSERGUI::LOG: Writing recipe to ${GPI_REDUCED_DATA_DIR}recipes/140515/auto_
             S20140515S0308_140515.waiting.xml
% PARSERGUI::LOG:     Queued /gemsoft/var/data/gpidata/ifs/queue//auto_S2014051
             5S0308_140515.waiting.xml
IDL> 
% LAUNCHER::CHECK_QUEUE: found 1 command(s) in the gui queue
% LAUNCHER::CHECK_QUEUE: Command is gpitv, with 2 argument(s).
% LAUNCHER::CHECK_QUEUE:     FILENAME = /gemsoft/var/data/gpidata/ifs/Reduced/1
            40515/S20140515S0308_spdc.fits
% LAUNCHER::CHECK_QUEUE:     SESSION =        5
GPITV:INFORMATION: Configuring GPItv for SPECTRAL MODE
GPITV:INFORMATION: inverting in x
GPITV:INFORMATION: Rotating with interpolation to -168.284
GPITV:INFORMATION: inverting in x
GPITV:INFORMATION: Rotating with interpolation to -168.284
Show Cube Slices
% PLOT: Not enough valid and unique points specified.
% Execution halted at: GPITV::ANGUPROF_REFRESH 18506
   /export/home/software/IDL/pipeline/gpitv/gpitv__define.pro
%                      GPITV::UPDATE_CHILD_WINDOWS 8114
   /export/home/software/IDL/pipeline/gpitv/gpitv__define.pro
%                      GPITV::SETUP_NEW_IMAGE 5781
   /export/home/software/IDL/pipeline/gpitv/gpitv__define.pro
%                      GPITV::READFITS  5545
   /export/home/software/IDL/pipeline/gpitv/gpitv__define.pro
%                      GPITV::OPEN      5396
   /export/home/software/IDL/pipeline/gpitv/gpitv__define.pro
%                      LAUNCHER::LAUNCH  473
   /export/home/software/IDL/pipeline/backbone/launcher__define.pro
%                      LAUNCHER::CHECK_QUEUE  415
   /export/home/software/IDL/pipeline/backbone/launcher__define.pro
%                      LAUNCHER::EVENT    98
   /export/home/software/IDL/pipeline/backbone/launcher__define.pro
%                      LAUNCHER_EVENT     39
   /export/home/software/IDL/pipeline/backbone/launcher__define.pro
%                      WIDGET_PROCESS_EVENTS
%                      $MAIN$

**Comment by mperrin** [comment] 2016-08-05 21:06
Legacy Rejected/wontfix issue migrated from redmine issue tracker. Originally filed by @semaphoreP on 2014-05-15 

@semaphoreP do you have any recollection about this at this time? I'm guessing not.

**Comment by semaphoreP** [comment] 2016-08-05 21:27
No, and I can't reproduce the error anymore so I'm closing this

**Closed as completed by semaphoreP** 2016-08-05 21:27 UTC
Labels: bug, wontfix
